#!/bin/bash
cat << EOF
System Report generated by $USER

System Info
------------
EOF
# Comments:
# L 11 grep filter for "=", head -1 gets first line from the "=", awk -F grabs what is after the "=" and tr -d removes quotations
# L 23 similar idea, added sort on uniques
# L 25 -F 'Gi' splits line, then {print $1 FS} statement makes awk print the memory usage value
# L 33 uses -I and filters the output to get first IP address using awk '{print $1}'
# L 35 excludes loopback from showing, shows 'ens' using grep, and cuts out what we dont need 
# L 42 wc -l counts lines in the output to show process count.
cat << EOF
Hostname: $(hostname)
OS: $(cat /etc/os-release | grep "=" | head -1 |  awk -F '=' '{print $2}' | tr -d '"')
Uptime: $(uptime -p)

Hardware Information
------------
CPU: $(lscpu | grep "Model name" | awk -F 'CPU' '{print $1 FS}')
SPEED: $(sudo lshw -class processor | grep size | awk '{print $2}'| sort -u)
MAX SPEED: $(lscpu | grep "CPU max MHz" | awk '{print $4}')
RAM: $(free -ht |  grep "Mem:" | awk -F 'Gi' '{print $1 FS}')
Disk: $(lsblk --nodeps --noheadings -o NAME,MODEL,SIZE | grep -v "loop")
Video: $(lspci | grep "VGA compatible controller" | awk -F ': ' '{print $2}')

Network Information
------------
FQDN: $(hostname --fqdn)
Host Address: $(hostname -i)
Gateway IP: $(hostname -I | awk '{print $1}')
DNS Server: $(cat /etc/resolv.conf | grep "nameserver")
InterfaceName: $(ip addr | grep -v "lo" | grep "ens" | cut -d':' -f2)
IP Address: $(ip -4 addr show | awk '/inet / {print $2; exit}')

System Status
------------
Users Logged In: $(who -sq)
Disk Space: $(df -h | awk '/^\/dev\// {printf "%s: %s\n", $6, $4}')
Process Count: $(ps -e --no-headers | wc -l)
Load Averages: $(uptime | awk -F'average: ' '{print $2}')
Memory Allocation: $(free -h | awk '/Mem/ {print $3 "/" $2}')
Listening Network Port: $(netstat -tuln | grep 'LISTEN')
UFW Rules: $(sudo ufw status)
EOF
# L 45 -t, finds TCP connections should be displayed. -u: find UDP connections should be displayed -l: Limits the output. -n: IP addresses
