
#!/bin/bash
cat << EOF
System Report generated by $USER

System Info
------------
Hostname: $(hostname)
OS: $(cat /etc/os-release | grep "=" | head -1 |  awk -F '=' '{print $2}' | tr -d '"')
Uptime: $(uptime -p)

Hardware Information
------------
CPU: $(lscpu | grep "Model name" | awk -F 'CPU' '{print $1 FS}')
SPEED: $(sudo lshw -class processor|grep size| awk '{print $2}'|sort -u)
MAX SPEED: $(lscpu | grep "CPU max MHz" | awk '{print $4}')
RAM: $(free -ht |  grep "Mem:" | awk -F 'Gi' '{print $1 FS}')
Disk: $(lsblk --nodeps --noheadings -o NAME,MODEL,SIZE | grep -v "loop")
Video: $(lspci | grep "VGA compatible controller" | awk -F ': ' '{print $2}')

Network Information
------------
FQDN: $(hostname --fqdn)
Host Address: $(hostname -i)
Gateway IP: $(hostname -I | awk '{print $1}')
DNS Server: $(cat /etc/resolv.conf | grep "nameserver")
InterfaceName: $(ip addr | grep -v "lo" | grep "ens" | cut -d':' -f2)
IP Address: $(ip -4 addr show | awk '/inet / {print $2; exit}')

System Status
------------
Users Logged In: $(who -sq)
Disk Space: $(df -h | awk '/^\/dev\// {printf "%s: %s\n", $6, $4}')
Process Count: $(ps -e --no-headers | wc -l)
Load Averages: $(uptime | awk -F'average: ' '{print $2}')
Memory Allocation: $(free -h | awk '/Mem/ {print $3 "/" $2}')
Listening Network Port: $(netstat -tuln | grep 'LISTEN')
UFW Rules: $(sudo ufw status)

EOF
